In [2]:
import numpy as np


In [6]:
np.__version__

'1.20.3'

In [8]:
np?

Type:        module
String form: <module 'numpy' from 'C:\\Users\\Asus\\anaconda3\\Anaconda\\lib\\site-packages\\numpy\\__init__.py'>
File:        c:\users\asus\anaconda3\anaconda\lib\site-packages\numpy\__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://www.scipy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::


In [9]:
np.array([range(i, i + 3) for i in [2, 4, 6]])


array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [15]:
np.empty(4)


array([8.48573491e-312, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000])

In [16]:
np.zeros(10)


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [18]:
np.ones((3,5),dtype = int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [23]:
np.full((3,5),3.14, dtype=int)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [28]:
np.arange(0,100,5) # x1 = 0 , xn = 100, xk += 5

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [31]:
a = np.linspace(0,10, 5 )
a

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [32]:
type(a)

numpy.ndarray

In [33]:
np.random.random((3,2))

array([[0.68808398, 0.9375861 ],
       [0.79992238, 0.2018164 ],
       [0.74765332, 0.04447352]])

In [35]:
np.random.normal(5,1,(2,4))

array([[4.45393503, 4.86297131, 6.63449862, 4.62592798],
       [3.86803463, 5.57180995, 3.49996997, 2.90072487]])

In [37]:
np.random.randint(10,50,(5,5))

array([[12, 42, 10, 20, 49],
       [25, 18, 23, 41, 37],
       [12, 19, 33, 35, 46],
       [35, 46, 41, 22, 31],
       [45, 15, 19, 27, 12]])

In [41]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [44]:
np.empty((3,4))

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [66]:
arr = np.zeros((2,4,5), dtype = np.int64)

In [67]:
arr

array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]], dtype=int64)

In [68]:
arr.dtype

dtype('int64')

In [69]:
arr.shape

(2, 4, 5)

In [70]:
arr.ndim

3

In [71]:
arr.size

40

In [72]:
arr.itemsize

8

In [73]:
arr.nbytes

320

In [77]:
arr = np.random.randint(10,50,(3,4,5))
arr


array([[[13, 41, 20, 11, 11],
        [17, 24, 48, 29, 15],
        [38, 31, 35, 47, 23],
        [14, 29, 40, 36, 12]],

       [[41, 35, 31, 31, 33],
        [40, 41, 35, 38, 39],
        [48, 19, 13, 21, 22],
        [31, 29, 12, 44, 20]],

       [[43, 15, 17, 45, 44],
        [30, 16, 40, 22, 29],
        [49, 10, 32, 32, 48],
        [15, 29, 24, 48, 19]]])

In [78]:
arr[0][1][3]

29

In [79]:
arr[0][1][3] = 290

In [80]:
arr

array([[[ 13,  41,  20,  11,  11],
        [ 17,  24,  48, 290,  15],
        [ 38,  31,  35,  47,  23],
        [ 14,  29,  40,  36,  12]],

       [[ 41,  35,  31,  31,  33],
        [ 40,  41,  35,  38,  39],
        [ 48,  19,  13,  21,  22],
        [ 31,  29,  12,  44,  20]],

       [[ 43,  15,  17,  45,  44],
        [ 30,  16,  40,  22,  29],
        [ 49,  10,  32,  32,  48],
        [ 15,  29,  24,  48,  19]]])

In [81]:
arr[-1][-1][-3]

24

In [82]:
arr[-1][-1][-3] = 4.9999 #The reason is casting

In [83]:
arr


array([[[ 13,  41,  20,  11,  11],
        [ 17,  24,  48, 290,  15],
        [ 38,  31,  35,  47,  23],
        [ 14,  29,  40,  36,  12]],

       [[ 41,  35,  31,  31,  33],
        [ 40,  41,  35,  38,  39],
        [ 48,  19,  13,  21,  22],
        [ 31,  29,  12,  44,  20]],

       [[ 43,  15,  17,  45,  44],
        [ 30,  16,  40,  22,  29],
        [ 49,  10,  32,  32,  48],
        [ 15,  29,   4,  48,  19]]])

In [85]:
arr[-1][2][0:3] = [1,2,3]

In [86]:
arr


array([[[ 13,  41,  20,  11,  11],
        [ 17,  24,  48, 290,  15],
        [ 38,  31,  35,  47,  23],
        [ 14,  29,  40,  36,  12]],

       [[ 41,  35,  31,  31,  33],
        [ 40,  41,  35,  38,  39],
        [ 48,  19,  13,  21,  22],
        [ 31,  29,  12,  44,  20]],

       [[ 43,  15,  17,  45,  44],
        [ 30,  16,  40,  22,  29],
        [  1,   2,   3,  32,  48],
        [ 15,  29,   4,  48,  19]]])

In [87]:
arr[-1][1][0:5:2] = [1,2,3]

In [88]:
arr

array([[[ 13,  41,  20,  11,  11],
        [ 17,  24,  48, 290,  15],
        [ 38,  31,  35,  47,  23],
        [ 14,  29,  40,  36,  12]],

       [[ 41,  35,  31,  31,  33],
        [ 40,  41,  35,  38,  39],
        [ 48,  19,  13,  21,  22],
        [ 31,  29,  12,  44,  20]],

       [[ 43,  15,  17,  45,  44],
        [  1,  16,   2,  22,   3],
        [  1,   2,   3,  32,  48],
        [ 15,  29,   4,  48,  19]]])

In [95]:
arr[0][:4][:5] = np.ones((4,5), dtype = 'float')

In [96]:
arr


array([[[ 1,  1,  1,  1,  1],
        [ 1,  1,  1,  1,  1],
        [ 1,  1,  1,  1,  1],
        [ 1,  1,  1,  1,  1]],

       [[41, 35, 31, 31, 33],
        [40, 41, 35, 38, 39],
        [48, 19, 13, 21, 22],
        [31, 29, 12, 44, 20]],

       [[43, 15, 17, 45, 44],
        [ 1, 16,  2, 22,  3],
        [ 1,  2,  3, 32, 48],
        [15, 29,  4, 48, 19]]])

#
Subarrays

In [97]:
arr


array([[[ 1,  1,  1,  1,  1],
        [ 1,  1,  1,  1,  1],
        [ 1,  1,  1,  1,  1],
        [ 1,  1,  1,  1,  1]],

       [[41, 35, 31, 31, 33],
        [40, 41, 35, 38, 39],
        [48, 19, 13, 21, 22],
        [31, 29, 12, 44, 20]],

       [[43, 15, 17, 45, 44],
        [ 1, 16,  2, 22,  3],
        [ 1,  2,  3, 32, 48],
        [15, 29,  4, 48, 19]]])

In [110]:
x = arr[2,:3,:3].copy()

In [111]:
x

array([[43, 15, 17],
       [ 1, 16,  2],
       [ 1,  2,  3]])

In [112]:
x2 = x.copy()

In [113]:
x2

array([[43, 15, 17],
       [ 1, 16,  2],
       [ 1,  2,  3]])

In [114]:
x2.reshape((1,9))

array([[43, 15, 17,  1, 16,  2,  1,  2,  3]])

In [115]:
x2

array([[43, 15, 17],
       [ 1, 16,  2],
       [ 1,  2,  3]])

In [116]:
x2[np.newaxis, :]


array([[[43, 15, 17],
        [ 1, 16,  2],
        [ 1,  2,  3]]])

In [117]:
x2.shape

(3, 3)

In [118]:
x2.ndim

2

In [119]:
x2[np.newaxis, :].ndim

3

In [127]:
A = np.array([[1,2,3],
             [4,6,5],
             [7,4,1]])

B = np.array([[8,2,4],
             [9,4,5],
             [7,1,1]])

np.concatenate([A,B], axis=1)

array([[1, 2, 3, 8, 2, 4],
       [4, 6, 5, 9, 4, 5],
       [7, 4, 1, 7, 1, 1]])

In [128]:
np.hstack([A,B])

array([[1, 2, 3, 8, 2, 4],
       [4, 6, 5, 9, 4, 5],
       [7, 4, 1, 7, 1, 1]])

In [129]:
np.vstack([A,B])

array([[1, 2, 3],
       [4, 6, 5],
       [7, 4, 1],
       [8, 2, 4],
       [9, 4, 5],
       [7, 1, 1]])

In [130]:
np.dstack([A,B])

array([[[1, 8],
        [2, 2],
        [3, 4]],

       [[4, 9],
        [6, 4],
        [5, 5]],

       [[7, 7],
        [4, 1],
        [1, 1]]])

### split

In [131]:
array = np.array([1,5,3,6,7,6,81,2,4])

In [133]:
m,n,z = np.split(array, [3,6])

In [135]:
print(m ,n ,z)

[1 5 3] [6 7 6] [81  2  4]


In [136]:
array_two_dim = np.random.randint(0,15,(3,3))

In [137]:
array_two_dim


array([[12,  5,  2],
       [ 9, 11, 14],
       [ 6,  5,  8]])

In [146]:
np.vsplit(array_two_dim, [1])

[array([[12,  5,  2]]),
 array([[ 9, 11, 14],
        [ 6,  5,  8]])]

In [147]:
np.hsplit(array_two_dim, [1])

[array([[12],
        [ 9],
        [ 6]]),
 array([[ 5,  2],
        [11, 14],
        [ 5,  8]])]

## fancy index


In [152]:
a = np.array([1,2,5,6,4])

b = [1,2]

a[b]

array([2, 5])

In [154]:
b = np.arange(0,16).reshape((4,4))

In [155]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [158]:
i = [2,3]

j = [1,2]

b[i,j]

array([ 9, 14])

In [3]:
w = np.array([1,5,6,8,7,45,6])

In [4]:
w


array([ 1,  5,  6,  8,  7, 45,  6])

In [6]:
w[w>7]

array([ 8, 45])

In [7]:
w[w<=7]

array([1, 5, 6, 7, 6])

In [8]:
w*7

array([  7,  35,  42,  56,  49, 315,  42])

In [9]:
w/5

array([0.2, 1. , 1.2, 1.6, 1.4, 9. , 1.2])

In [10]:
w**2

array([   1,   25,   36,   64,   49, 2025,   36], dtype=int32)

In [11]:
w//5

array([0, 1, 1, 1, 1, 9, 1], dtype=int32)

In [13]:
w-1

array([ 0,  4,  5,  7,  6, 44,  5])

2x1 + 3x2 = 8
3x1 + 5x2 = 13

In [17]:
a = np.array([[2,3],[3,5]])
b = np.array([8,13])

x = np.linalg.solve(a,b)

In [18]:
x

array([1., 2.])

In [20]:
w

array([ 1,  5,  6,  8,  7, 45,  6])

In [21]:
np.add(w,2)

array([ 3,  7,  8, 10,  9, 47,  8])

In [23]:
np.subtract(w,2)

array([-1,  3,  4,  6,  5, 43,  4])

In [24]:
np.multiply(w,2)

array([ 2, 10, 12, 16, 14, 90, 12])

In [26]:
np.divide(w,5)

array([0.2, 1. , 1.2, 1.6, 1.4, 9. , 1.2])

In [27]:
w/5

array([0.2, 1. , 1.2, 1.6, 1.4, 9. , 1.2])

In [28]:
w*2

array([ 2, 10, 12, 16, 14, 90, 12])

In [29]:
w//6

array([0, 0, 1, 1, 1, 7, 1], dtype=int32)

In [31]:
np.floor_divide(w,6)

array([0, 0, 1, 1, 1, 7, 1], dtype=int32)

In [32]:
w**2

array([   1,   25,   36,   64,   49, 2025,   36], dtype=int32)

In [34]:
np.power(w,2)

array([   1,   25,   36,   64,   49, 2025,   36], dtype=int32)

In [35]:
np.mod(w,5)

array([1, 0, 1, 3, 2, 0, 1], dtype=int32)

In [36]:
w%5

array([1, 0, 1, 3, 2, 0, 1], dtype=int32)

In [40]:
np.absolute(np.array([-2,5,-7,9,3,21]))

array([ 2,  5,  7,  9,  3, 21])

In [41]:
abs(np.array([-2,5,-7,9,3,21]))

array([ 2,  5,  7,  9,  3, 21])

In [43]:
q = np.array([[-2, 5, -7],
              [4, 6, 2],
              [-8, 5, 3]])

In [44]:
q+1

array([[-1,  6, -6],
       [ 5,  7,  3],
       [-7,  6,  4]])

In [45]:
abs(q)

array([[2, 5, 7],
       [4, 6, 2],
       [8, 5, 3]])

In [46]:
np.abs(q)

array([[2, 5, 7],
       [4, 6, 2],
       [8, 5, 3]])

In [49]:
z = np.array([
    [4+4j, 4+8j, 1+6j],
    [7+2j, 1+1j, 2+2j]
], dtype = complex)

In [50]:
np.abs(z)

array([[5.65685425, 8.94427191, 6.08276253],
       [7.28010989, 1.41421356, 2.82842712]])

# Trigonometric functions

In [51]:
tetha = np.linspace(0,np.pi, 3)


In [52]:
tetha


array([0.        , 1.57079633, 3.14159265])

In [54]:
np.sin(tetha)

array([0.0000000e+00, 1.0000000e+00, 1.2246468e-16])

In [55]:
np.cos(tetha)

array([ 1.000000e+00,  6.123234e-17, -1.000000e+00])

In [57]:
np.tan(tetha)

array([ 0.00000000e+00,  1.63312394e+16, -1.22464680e-16])

# Inverse trigonometric functions

In [58]:
k = np.array( [-1, 0, 1])

In [62]:
x =np.array( [np.arccos(k),np.arcsin(k),np.arctan(k)])

In [63]:
x

array([[ 3.14159265,  1.57079633,  0.        ],
       [-1.57079633,  0.        ,  1.57079633],
       [-0.78539816,  0.        ,  0.78539816]])

In [64]:
x.ndim

2